/**
 * Single source of truth for all icons used across Tinute.
 * All components and files MUST import icons from this file, never directly from 'lucide-react'.
 * Do NOT use emojis or custom SVGs for UI icons.
 */
export {
  AlertCircle,
  AlertOctagon,
  AlertTriangle,
  Archive,
  ArrowLeftRight,
  Award,
  Ban,
  CheckCircle2,
  ChevronDown,
  Columns,
  Cpu,
  Download,
  FileImage,
  Flame,
  Image as ImageIcon,
  Laptop,
  Layers,
  Maximize2,
  Moon,
  RotateCw,
  Settings2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sliders,
  SlidersHorizontal,
  Sun,
  Terminal,
  Trash2,
  Trophy,
  UploadCloud,
  Volume2,
  VolumeX,
  X,
  Zap,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';
